services:
  portfolio:
    image: ghcr.io/cheeselad/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-svelte.entrypoints=https"
      - "traefik.http.routers.portfolio-svelte.rule=Host(`portfolio.jakefarrell.ie`)"
      - "traefik.http.routers.personal-site.entrypoints=https"
      - "traefik.http.routers.personal-site.rule=Host(`www.jakefarrell.ie`)"
      - "traefik.http.routers.personal-site-base-url.entrypoints=https"
      - "traefik.http.routers.personal-site-base-url.rule=Host(`jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true
