services:
  nubar:
    image: ghcr.io/cheeselad/nubar:latest
    container_name: nubar
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nubar-site.entrypoints=https"
      - "traefik.http.routers.nubar-site.rule=Host(`www.nubar.xyz`)"
      - "traefik.http.routers.nubar-site-base-url.entrypoints=https"
      - "traefik.http.routers.nubar-site-base-url.rule=Host(`nubar.xyz`)"

networks:
  default:
    name: traefik_net
    external: true