services:
  ca298-pizzashop:
    image: ghcr.io/cheeselad/ca298-pizzashop:latest
    container_name: ca298-pizzashop
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ca298-pizzashop.entrypoints=https"
      - "traefik.http.routers.ca298-pizzashop.rule=Host(`pizzashop.jakefarrell.ie`)"
    volumes:
      - ./db.sqlite3:/app/pizzashop/db.sqlite3

networks:
  default:
    name: traefik_net
    external: true