services:
  dcufotosoc-generator:
    image: ghcr.io/cheeselad/fotosoc-newsletter-generator-frontend:latest
    container_name: dcufotosoc-generator
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcufotosoc-generator.entrypoints=https"
      - "traefik.http.routers.dcufotosoc-generator.rule=Host(`generator.dcufotosoc.ie`)"
      - "traefik.http.routers.dcufotosoc-generator.tls.certresolver=dcufotosoc"
    environment:
      - VITE_API_URL=$VITE_API_URL
      - VITE_LISTMONK_MODE=$VITE_LISTMONK_MODE

networks:
  default:
    name: traefik_net
    external: true